import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#f6faf7",
  },
  screen: {
    flex: 1,
  },
  topBar: {
    alignItems: "center",
    backgroundColor: "#f6faf7",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 8,
  },
  menuAnchor: {
    position: "relative",
  },
  menuButton: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#d4d4d8",
    borderRadius: 14,
    borderWidth: 1,
    height: 42,
    justifyContent: "center",
    width: 42,
  },
  menuButtonPressed: {
    opacity: 0.82,
  },
  menuButtonSpacer: {
    height: 42,
    width: 42,
  },
  menuDots: {
    color: "#111827",
    fontSize: 22,
    fontWeight: "800",
    lineHeight: 24,
    textAlign: "center",
  },
  menuSheet: {
    backgroundColor: "rgba(255, 255, 255, 0.74)",
    borderColor: "rgba(16, 185, 129, 0.28)",
    borderRadius: 16,
    borderWidth: 1,
    minWidth: 220,
    overflow: "hidden",
    position: "absolute",
    right: 0,
    shadowColor: "#065f46",
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.18,
    shadowRadius: 22,
    top: 48,
    zIndex: 50,
  },
  menuGlassTint: {
    backgroundColor: "rgba(255, 255, 255, 0.60)",
  },
  menuItem: {
    borderBottomColor: "rgba(16, 185, 129, 0.16)",
    borderBottomWidth: StyleSheet.hairlineWidth,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  menuItemText: {
    color: "#111827",
    fontSize: 15,
    fontWeight: "700",
  },
  content: {
    paddingHorizontal: 20,
    paddingBottom: 24,
    paddingTop: 16,
  },
  contentCompact: {
    paddingHorizontal: 16,
  },
  hero: {
    gap: 8,
    marginBottom: 16,
  },
  homeHeroCard: {
    backgroundColor: "#ffffff",
    borderColor: "#d1fae5",
    borderRadius: 24,
    borderWidth: 1,
    gap: 10,
    marginBottom: 16,
    padding: 20,
  },
  homeCard: {
    backgroundColor: "#ffffff",
    borderColor: "#d4d4d8",
    borderRadius: 22,
    borderWidth: 1,
    gap: 10,
    marginBottom: 16,
    padding: 18,
  },
  cookbookSectionHeader: {
    marginBottom: 8,
    paddingHorizontal: 4,
  },
  cookbookControlsRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 12,
  },
  cookbookSearchWrap: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#d4d4d8",
    borderRadius: 16,
    borderWidth: 1,
    flex: 1,
    flexDirection: "row",
    gap: 10,
    minHeight: 48,
    paddingHorizontal: 14,
  },
  cookbookSearchInput: {
    color: "#111827",
    flex: 1,
    fontSize: 15,
    paddingVertical: 0,
  },
  cookbookSearchClearButton: {
    alignItems: "center",
    backgroundColor: "#f4f4f5",
    borderRadius: 999,
    height: 24,
    justifyContent: "center",
    width: 24,
  },
  cookbookSortButton: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#d1fae5",
    borderRadius: 16,
    borderWidth: 1,
    height: 48,
    justifyContent: "center",
    width: 48,
  },
  cookbookSortButtonActive: {
    backgroundColor: "#ecfdf5",
    borderColor: "#10b981",
  },
  offlineNoticeCard: {
    backgroundColor: "#f0fdf4",
    borderColor: "#bbf7d0",
    borderRadius: 18,
    borderWidth: 1,
    gap: 6,
    marginBottom: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  offlineNoticeTitle: {
    color: "#166534",
    fontSize: 14,
    fontWeight: "800",
  },
  offlineNoticeCopy: {
    color: "#15803d",
    fontSize: 14,
    lineHeight: 20,
  },
  homeBody: {
    color: "#4b5563",
    fontSize: 15,
    lineHeight: 23,
  },
  heroImageCard: {
    backgroundColor: "#ffffff",
    borderColor: "#d4d4d8",
    borderRadius: 24,
    borderWidth: 1,
    marginBottom: 12,
    overflow: "hidden",
  },
  heroImageCardPressed: {
    opacity: 0.94,
  },
  heroImage: {
    aspectRatio: 4 / 3,
    width: "100%",
  },
  heroImageState: {
    alignItems: "center",
    aspectRatio: 4 / 3,
    backgroundColor: "#fafaf9",
    gap: 10,
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  heroImageSpinner: {
    marginBottom: 2,
  },
  heroImageStateText: {
    color: "#6b7280",
    fontSize: 14,
    textAlign: "center",
  },
  resultActionsRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 18,
  },
  resultActionsRowCompact: {
    gap: 8,
  },
  resultActionContent: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
  resultActionPrimary: {
    alignItems: "center",
    backgroundColor: "#10b981",
    borderRadius: 16,
    flex: 1,
    minHeight: 48,
    justifyContent: "center",
    minWidth: 0,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  resultActionCompact: {
    paddingHorizontal: 8,
  },
  resultActionPrimaryText: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "700",
    textAlign: "center",
  },
  resultActionTextCompact: {
    fontSize: 12,
  },
  resultActionSecondary: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#d4d4d8",
    borderRadius: 16,
    borderWidth: 1,
    flex: 1,
    minHeight: 48,
    justifyContent: "center",
    minWidth: 0,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  resultActionSecondaryText: {
    color: "#374151",
    fontSize: 13,
    fontWeight: "700",
    textAlign: "center",
  },
  deleteActionButton: {
    borderColor: "#fecaca",
  },
  deleteActionText: {
    color: "#b91c1c",
    fontSize: 13,
    fontWeight: "700",
    textAlign: "center",
  },
  resultActionPressed: {
    opacity: 0.86,
  },
  resultActionSecondaryPressed: {
    backgroundColor: "#fafaf9",
  },
  formGroup: {
    gap: 10,
    marginTop: 6,
  },
  fieldLabel: {
    color: "#065f46",
    fontSize: 15,
    fontWeight: "700",
  },
  recipeInput: {
    backgroundColor: "#fafaf9",
    borderColor: "#d4d4d8",
    borderRadius: 18,
    borderWidth: 1,
    color: "#111827",
    fontSize: 15,
    lineHeight: 22,
    minHeight: 150,
    paddingHorizontal: 14,
    paddingVertical: 14,
    paddingBottom: 54,
  },
  recipeInputWrap: {
    position: "relative",
  },
  recipeInputIconButton: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#d1fae5",
    borderRadius: 14,
    borderWidth: 1,
    bottom: 12,
    height: 36,
    justifyContent: "center",
    position: "absolute",
    right: 12,
    width: 36,
  },
  optionGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  optionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  choiceChip: {
    backgroundColor: "#f4f4f5",
    borderColor: "#d4d4d8",
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  choiceChipSelected: {
    backgroundColor: "#ecfdf5",
    borderColor: "#10b981",
  },
  choiceChipText: {
    color: "#374151",
    fontSize: 14,
    fontWeight: "600",
    textTransform: "capitalize",
  },
  choiceChipTextSelected: {
    color: "#065f46",
  },
  levelChip: {
    alignItems: "center",
    backgroundColor: "#f4f4f5",
    borderColor: "#d4d4d8",
    borderRadius: 999,
    borderWidth: 1,
    height: 42,
    justifyContent: "center",
    width: 42,
  },
  levelChipSelected: {
    backgroundColor: "#ecfdf5",
    borderColor: "#10b981",
  },
  levelChipText: {
    color: "#374151",
    fontSize: 14,
    fontWeight: "700",
  },
  spiceHint: {
    color: "#065f46",
    fontSize: 14,
    fontWeight: "600",
  },
  homeActionGroup: {
    gap: 10,
    marginTop: 4,
  },
  homeBulletList: {
    gap: 10,
  },
  homeBullet: {
    color: "#374151",
    fontSize: 15,
    lineHeight: 22,
  },
  cookbookCard: {
    backgroundColor: "#fafaf9",
    borderColor: "#d1fae5",
    borderRadius: 18,
    borderWidth: 1,
    marginBottom: 12,
    padding: 14,
  },
  cookbookCardRow: {
    alignItems: "stretch",
    flexDirection: "row",
    gap: 12,
  },
  cookbookCardMainPressable: {
    flex: 1,
  },
  cookbookCardContentRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
  },
  cookbookCardImage: {
    borderRadius: 16,
    height: 72,
    width: 96,
  },
  cookbookCardImageCompact: {
    height: 64,
    width: 84,
  },
  cookbookCardImagePlaceholder: {
    alignItems: "center",
    backgroundColor: "#f0fdf4",
    borderColor: "#d1fae5",
    borderRadius: 16,
    borderWidth: 1,
    height: 72,
    justifyContent: "center",
    width: 96,
  },
  cookbookCardBody: {
    flex: 1,
    gap: 6,
    minWidth: 0,
  },
  cookbookCardActions: {
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 2,
    width: 40,
  },
  cookbookCardActionsCompact: {
    width: 34,
  },
  cookbookCardTitle: {
    color: "#111827",
    fontSize: 16,
    fontWeight: "800",
  },
  cookbookCardTitleCompact: {
    fontSize: 15,
  },
  cookbookCardDate: {
    color: "#047857",
    fontSize: 12,
    fontWeight: "700",
    textAlign: "center",
  },
  cookbookCardMeta: {
    color: "#6b7280",
    fontSize: 14,
    lineHeight: 21,
  },
  cookbookDeleteButton: {
    alignItems: "center",
    backgroundColor: "#fff1f2",
    borderColor: "#fecdd3",
    borderRadius: 12,
    borderWidth: 1,
    height: 32,
    justifyContent: "center",
    width: 32,
  },
  cookbookDeleteButtonPressed: {
    opacity: 0.82,
  },
  cookbookListFooter: {
    alignItems: "center",
    justifyContent: "center",
    minHeight: 44,
    paddingBottom: 8,
    paddingTop: 4,
  },
  emptyCookbookCard: {
    gap: 12,
    paddingVertical: 6,
  },
  emptyCookbookTitle: {
    color: "#111827",
    fontSize: 18,
    fontWeight: "800",
  },
  emptyCookbookCopy: {
    color: "#4b5563",
    fontSize: 15,
    lineHeight: 23,
  },
  statusCopy: {
    color: "#4b5563",
    fontSize: 15,
    lineHeight: 23,
  },
  brand: {
    color: "#111827",
    fontFamily: "Pacifico_400Regular",
    fontSize: 24,
    lineHeight: 32,
  },
  kicker: {
    alignSelf: "flex-start",
    backgroundColor: "#10b981",
    borderRadius: 999,
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "700",
    overflow: "hidden",
    paddingHorizontal: 12,
    paddingVertical: 6,
    textTransform: "uppercase",
  },
  title: {
    color: "#111827",
    fontSize: 34,
    fontWeight: "800",
    lineHeight: 40,
  },
  titleCompact: {
    fontSize: 30,
    lineHeight: 36,
  },
  titleVeryCompact: {
    fontSize: 27,
    lineHeight: 33,
  },
  meta: {
    color: "#c2410c",
    fontSize: 14,
    fontWeight: "600",
  },
  pendingCopy: {
    color: "#4b5563",
    fontSize: 16,
    lineHeight: 24,
  },
  summary: {
    color: "#4b5563",
    fontSize: 17,
    lineHeight: 28,
  },
  captureCard: {
    backgroundColor: "#ffffff",
    borderColor: "#d4d4d8",
    borderRadius: 28,
    borderWidth: 1,
    overflow: "hidden",
    width: 520,
  },
  visibleCard: {
    backgroundColor: "#ffffff",
    borderColor: "#d4d4d8",
    borderRadius: 24,
    borderWidth: 1,
    marginBottom: 16,
    padding: 18,
  },
  importCard: {
    backgroundColor: "#ffffff",
    borderColor: "#d4d4d8",
    borderRadius: 24,
    borderWidth: 1,
    gap: 14,
    marginBottom: 16,
    padding: 18,
  },
  compactImportCard: {
    backgroundColor: "#fafaf9",
    borderColor: "#e4e4e7",
    borderRadius: 20,
    borderWidth: 1,
    gap: 12,
    marginTop: 8,
    overflow: "hidden",
    padding: 12,
  },
  compactImportHeader: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 12,
  },
  compactImportImage: {
    borderRadius: 14,
    width: 84,
  },
  compactImportImageCompact: {
    width: 72,
  },
  compactImportTextBlock: {
    flex: 1,
    gap: 4,
  },
  imageViewerOverlay: {
    alignItems: "center",
    backgroundColor: "rgba(17, 24, 39, 0.94)",
    flex: 1,
    justifyContent: "center",
  },
  imageViewerSafeArea: {
    flex: 1,
    justifyContent: "center",
    width: "100%",
  },
  imageViewerBody: {
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 20,
    width: "100%",
  },
  imageViewerImage: {
    aspectRatio: 4 / 3,
    borderRadius: 18,
    maxHeight: "85%",
    width: "100%",
  },
  hiddenCaptureHost: {
    left: -10000,
    position: "absolute",
    top: 0,
  },
  captureHeader: {
    backgroundColor: "#ecfdf5",
    gap: 8,
    paddingHorizontal: 22,
    paddingVertical: 22,
  },
  captureHeroImage: {
    aspectRatio: 4 / 3,
    width: "100%",
  },
  captureHeroImageFallback: {
    alignItems: "center",
    aspectRatio: 4 / 3,
    backgroundColor: "#fafaf9",
    borderBottomColor: "#e4e4e7",
    borderBottomWidth: 1,
    justifyContent: "center",
    paddingHorizontal: 18,
  },
  captureHeroImageFallbackText: {
    color: "#6b7280",
    fontSize: 14,
    textAlign: "center",
  },
  captureBrandRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  captureBrand: {
    color: "#065f46",
    fontSize: 18,
    fontWeight: "800",
  },
  captureStamp: {
    backgroundColor: "#ffffff",
    borderRadius: 999,
    color: "#047857",
    fontSize: 12,
    fontWeight: "700",
    overflow: "hidden",
    paddingHorizontal: 10,
    paddingVertical: 6,
    textTransform: "uppercase",
  },
  captureEyebrow: {
    color: "#c2410c",
    fontSize: 14,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  captureTitle: {
    color: "#111827",
    fontSize: 34,
    fontWeight: "800",
    lineHeight: 40,
  },
  captureSubtitle: {
    color: "#4b5563",
    fontSize: 17,
    lineHeight: 25,
  },
  card: {
    gap: 2,
    padding: 22,
  },
  capturePanel: {
    backgroundColor: "#fafaf9",
    borderRadius: 18,
    padding: 16,
  },
  capturePanelTitle: {
    color: "#065f46",
    fontSize: 18,
    fontWeight: "800",
    marginBottom: 10,
  },
  sectionTitle: {
    color: "#065f46",
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 12,
  },
  sectionHeaderRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
    marginBottom: 12,
  },
  sectionHeaderTitle: {
    color: "#065f46",
    fontSize: 18,
    fontWeight: "700",
    lineHeight: 22,
  },
  badgeRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  badge: {
    backgroundColor: "#ecfdf5",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  badgeText: {
    color: "#065f46",
    fontSize: 13,
    fontWeight: "600",
  },
  captureTagGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  captureTag: {
    backgroundColor: "#ffffff",
    borderColor: "#d1fae5",
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  captureTagLabel: {
    color: "#065f46",
    fontSize: 14,
    fontWeight: "600",
  },
  divider: {
    backgroundColor: "#e4e4e7",
    height: 1,
    marginVertical: 16,
  },
  listRow: {
    backgroundColor: "#f0fdf4",
    borderColor: "#dcfce7",
    borderRadius: 16,
    borderWidth: 1,
    gap: 2,
    marginBottom: 10,
    padding: 12,
  },
  listPrimary: {
    color: "#111827",
    fontSize: 15,
    fontWeight: "600",
  },
  listSecondary: {
    color: "#6b7280",
    fontSize: 13,
  },
  swapCard: {
    backgroundColor: "#ecfdf5",
    borderColor: "#d1fae5",
    borderRadius: 18,
    borderWidth: 1,
    gap: 6,
    marginBottom: 10,
    padding: 14,
  },
  swapTitle: {
    color: "#111827",
    fontSize: 15,
    fontWeight: "600",
  },
  swapReason: {
    color: "#6b7280",
    fontSize: 13,
    lineHeight: 19,
  },
  shoppingRow: {
    alignItems: "flex-start",
    borderRadius: 16,
    flexDirection: "row",
    gap: 12,
    marginBottom: 12,
    paddingHorizontal: 6,
    paddingVertical: 6,
  },
  shoppingRowChecked: {
    opacity: 0.72,
  },
  shoppingCheckbox: {
    alignItems: "center",
    borderColor: "#10b981",
    borderRadius: 999,
    borderWidth: 1.5,
    height: 20,
    justifyContent: "center",
    marginTop: 2,
    width: 20,
  },
  shoppingCheckboxChecked: {
    backgroundColor: "#10b981",
    borderColor: "#10b981",
  },
  shoppingCheckboxTick: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 12,
  },
  shoppingTextBlock: {
    flex: 1,
  },
  checkedPrimaryText: {
    color: "#6b7280",
    textDecorationLine: "line-through",
  },
  checkedSecondaryText: {
    color: "#9ca3af",
    textDecorationLine: "line-through",
  },
  nutritionCard: {
    backgroundColor: "#fff7ed",
    borderColor: "#fed7aa",
    borderRadius: 18,
    borderWidth: 1,
    padding: 14,
  },
  nutritionCopy: {
    color: "#7c2d12",
    fontSize: 14,
    lineHeight: 21,
  },
  emptySectionCopy: {
    color: "#6b7280",
    fontSize: 14,
    lineHeight: 21,
  },
  stepRow: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 14,
  },
  stepIndex: {
    color: "#10b981",
    fontSize: 16,
    fontWeight: "800",
    width: 18,
  },
  stepText: {
    color: "#374151",
    flex: 1,
    fontSize: 15,
    lineHeight: 23,
  },
  captureNote: {
    backgroundColor: "#fff7ed",
    borderRadius: 18,
    marginTop: 2,
    padding: 14,
  },
  captureNoteLabel: {
    color: "#c2410c",
    fontSize: 13,
    fontWeight: "800",
    marginBottom: 6,
    textTransform: "uppercase",
  },
  captureNoteText: {
    color: "#7c2d12",
    fontSize: 15,
    lineHeight: 22,
  },
  captureFooter: {
    alignItems: "center",
    marginTop: 16,
    paddingHorizontal: 8,
  },
  captureFooterTitle: {
    color: "#111827",
    fontSize: 15,
    fontWeight: "800",
    marginBottom: 4,
    textAlign: "center",
  },
  captureFooterText: {
    color: "#6b7280",
    fontSize: 13,
    lineHeight: 19,
    textAlign: "center",
  },
  importCopy: {
    color: "#4b5563",
    fontSize: 15,
    lineHeight: 23,
  },
  importActions: {
    gap: 10,
  },
  previewCard: {
    backgroundColor: "#fafaf9",
    borderColor: "#e4e4e7",
    borderRadius: 20,
    borderWidth: 1,
    gap: 12,
    overflow: "hidden",
    padding: 12,
  },
  previewImage: {
    borderRadius: 16,
    width: "100%",
  },
  previewTextBlock: {
    gap: 4,
  },
  previewActions: {
    gap: 10,
  },
  previewTitle: {
    color: "#111827",
    fontSize: 17,
    fontWeight: "700",
  },
  previewMeta: {
    color: "#047857",
    fontSize: 13,
    fontWeight: "600",
  },
  previewCopy: {
    color: "#6b7280",
    fontSize: 14,
    lineHeight: 21,
  },
  extractedTextInput: {
    backgroundColor: "#fafaf9",
    borderColor: "#d4d4d8",
    borderRadius: 18,
    borderWidth: 1,
    color: "#111827",
    fontSize: 15,
    lineHeight: 22,
    minHeight: 240,
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  modalSafeArea: {
    backgroundColor: "#f6faf7",
    flex: 1,
  },
  modalKeyboardWrap: {
    flex: 1,
  },
  modalScrollView: {
    flex: 1,
  },
  modalScrollContent: {
    flexGrow: 1,
    paddingBottom: 40,
  },
  modalSheet: {
    backgroundColor: "#f6faf7",
    gap: 16,
    paddingHorizontal: 20,
    paddingTop: 18,
  },
  modalHeader: {
    alignItems: "flex-start",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  modalHeaderCompact: {
    gap: 12,
  },
  modalHeaderTextBlock: {
    flex: 1,
    marginRight: 12,
  },
  modalTitle: {
    color: "#111827",
    fontSize: 22,
    fontWeight: "800",
  },
  modalSubtitle: {
    color: "#6b7280",
    fontSize: 14,
    lineHeight: 21,
    marginTop: 4,
    maxWidth: 240,
  },
  modalCloseButton: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#d4d4d8",
    borderRadius: 14,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 42,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  modalCloseLabel: {
    color: "#111827",
    fontSize: 14,
    fontWeight: "700",
  },
  modalPreviewCard: {
    backgroundColor: "#ffffff",
    borderColor: "#d4d4d8",
    borderRadius: 22,
    borderWidth: 1,
    gap: 12,
    padding: 14,
  },
  modalEditorCard: {
    backgroundColor: "#ffffff",
    borderColor: "#d4d4d8",
    borderRadius: 22,
    borderWidth: 1,
    gap: 12,
    padding: 14,
  },
  modalSectionLabel: {
    color: "#065f46",
    fontSize: 15,
    fontWeight: "700",
  },
  modalPreviewImage: {
    borderRadius: 18,
    maxHeight: 240,
    width: "100%",
  },
  modalActions: {
    gap: 10,
    paddingBottom: 4,
  },
  emptyImportState: {
    backgroundColor: "#fafaf9",
    borderColor: "#e4e4e7",
    borderRadius: 20,
    borderStyle: "dashed",
    borderWidth: 1,
    gap: 6,
    padding: 16,
  },
  emptyImportTitle: {
    color: "#111827",
    fontSize: 16,
    fontWeight: "700",
  },
  emptyImportCopy: {
    color: "#6b7280",
    fontSize: 14,
    lineHeight: 21,
  },
});
