import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  safeArea: {
    flex: 1,
    backgroundColor: "#f6faf7",
  },
  screen: {
    flex: 1,
  },
  topBar: {
    alignItems: "center",
    backgroundColor: "#f6faf7",
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 20,
    paddingTop: 10,
  },
  menuAnchor: {
    position: "relative",
  },
  menuButton: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#d1fae5",
    borderRadius: 14,
    borderWidth: 1,
    height: 42,
    justifyContent: "center",
    width: 42,
  },
  menuButtonPressed: {
    opacity: 0.82,
  },
  menuButtonSpacer: {
    height: 42,
    width: 42,
  },
  menuDots: {
    color: "#111827",
    fontSize: 22,
    fontWeight: "800",
    lineHeight: 24,
    textAlign: "center",
  },
  menuSheet: {
    backgroundColor: "rgba(255, 255, 255, 0.74)",
    borderColor: "rgba(16, 185, 129, 0.28)",
    borderRadius: 16,
    borderWidth: 1,
    minWidth: 220,
    overflow: "hidden",
    position: "absolute",
    right: 0,
    shadowColor: "#065f46",
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.18,
    shadowRadius: 22,
    top: 48,
    zIndex: 50,
  },
  menuGlassTint: {
    backgroundColor: "rgba(255, 255, 255, 0.60)",
  },
  menuItem: {
    borderBottomColor: "rgba(16, 185, 129, 0.16)",
    borderBottomWidth: StyleSheet.hairlineWidth,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  menuItemText: {
    color: "#111827",
    fontSize: 15,
    fontWeight: "700",
  },
  content: {
    paddingHorizontal: 20,
    paddingBottom: 24,
    paddingTop: 10,
  },
  contentCompact: {
    paddingHorizontal: 16,
  },
  hero: {
    gap: 8,
    marginBottom: 16,
  },
  homeHeroCard: {
    backgroundColor: "#ffffff",
    borderColor: "#d1fae5",
    borderRadius: 24,
    borderWidth: 1,
    gap: 10,
    marginBottom: 16,
    padding: 20,
  },
  homeCard: {
    backgroundColor: "#ffffff",
    borderColor: "#d1fae5",
    borderRadius: 22,
    borderWidth: 1,
    gap: 10,
    marginBottom: 16,
    padding: 18,
  },
  homeHowItWorksCard: {
    backgroundColor: "#ffffff",
    borderColor: "#d1fae5",
    borderRadius: 22,
    borderWidth: 1,
    gap: 12,
    marginBottom: 16,
    padding: 18,
  },
  homeHowItWorksTitle: {
    color: "#065f46",
    fontSize: 18,
    fontWeight: "800",
  },
  homeHowItWorksList: {
    gap: 12,
  },
  homeHowItWorksRow: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 12,
  },
  homeHowItWorksStep: {
    alignItems: "center",
    backgroundColor: "#ecfdf5",
    borderColor: "#a7f3d0",
    borderRadius: 999,
    borderWidth: 1,
    height: 26,
    justifyContent: "center",
    marginTop: 2,
    width: 26,
  },
  homeHowItWorksStepText: {
    color: "#047857",
    fontSize: 13,
    fontWeight: "800",
  },
  homeHowItWorksCopy: {
    color: "#374151",
    flex: 1,
    fontSize: 15,
    lineHeight: 23,
  },
  cookbookSectionHeader: {
    marginBottom: 8,
    paddingHorizontal: 4,
  },
  cookbookControlsRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 12,
  },
  cookbookFilterRow: {
    flexDirection: "row",
    gap: 8,
    marginBottom: 12,
  },
  cookbookFilterChip: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#d1fae5",
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    minHeight: 40,
    justifyContent: "center",
    paddingHorizontal: 8,
  },
  cookbookFilterChipActive: {
    backgroundColor: "#047857",
    borderColor: "#047857",
  },
  cookbookFilterChipText: {
    color: "#047857",
    fontSize: 12,
    fontWeight: "900",
    textAlign: "center",
  },
  cookbookFilterChipTextActive: {
    color: "#ffffff",
  },
  cookbookSearchWrap: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#d1fae5",
    borderRadius: 16,
    borderWidth: 1,
    flex: 1,
    flexDirection: "row",
    gap: 10,
    minHeight: 48,
    paddingHorizontal: 14,
  },
  cookbookSearchInput: {
    color: "#111827",
    flex: 1,
    fontSize: 15,
    paddingVertical: 0,
  },
  cookbookSearchClearButton: {
    alignItems: "center",
    backgroundColor: "#f4f4f5",
    borderRadius: 999,
    height: 24,
    justifyContent: "center",
    width: 24,
  },
  cookbookSortButton: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#d1fae5",
    borderRadius: 16,
    borderWidth: 1,
    height: 48,
    justifyContent: "center",
    width: 48,
  },
  cookbookSortButtonActive: {
    backgroundColor: "#ecfdf5",
    borderColor: "#10b981",
  },
  offlineNoticeCard: {
    backgroundColor: "#f0fdf4",
    borderColor: "#bbf7d0",
    borderRadius: 18,
    borderWidth: 1,
    gap: 6,
    marginBottom: 12,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  offlineNoticeTitle: {
    color: "#166534",
    fontSize: 14,
    fontWeight: "800",
  },
  offlineNoticeCopy: {
    color: "#15803d",
    fontSize: 14,
    lineHeight: 20,
  },
  homeBody: {
    color: "#4b5563",
    fontSize: 15,
    lineHeight: 23,
  },
  heroImageCard: {
    backgroundColor: "#ffffff",
    borderColor: "#d1fae5",
    borderRadius: 24,
    borderWidth: 1,
    marginBottom: 12,
    overflow: "hidden",
  },
  heroImageCardPressed: {
    opacity: 0.94,
  },
  heroImage: {
    aspectRatio: 4 / 3,
    width: "100%",
  },
  heroImageState: {
    alignItems: "center",
    aspectRatio: 4 / 3,
    backgroundColor: "#fafaf9",
    gap: 10,
    justifyContent: "center",
    paddingHorizontal: 20,
  },
  heroImageSpinner: {
    marginBottom: 2,
  },
  premiumLoaderWrap: {
    alignItems: "center",
    height: 78,
    justifyContent: "center",
    marginBottom: 4,
    width: 78,
  },
  premiumLoaderGlow: {
    backgroundColor: "rgba(16, 185, 129, 0.20)",
    borderRadius: 999,
    height: 76,
    position: "absolute",
    width: 76,
  },
  premiumLoaderRing: {
    borderColor: "rgba(16, 185, 129, 0.22)",
    borderRadius: 999,
    borderTopColor: "#10b981",
    borderRightColor: "#34d399",
    borderWidth: 3,
    height: 58,
    width: 58,
  },
  premiumLoaderCore: {
    alignItems: "center",
    backgroundColor: "#ecfdf5",
    borderColor: "#a7f3d0",
    borderRadius: 999,
    borderWidth: 1,
    height: 28,
    justifyContent: "center",
    position: "absolute",
    width: 28,
  },
  premiumLoaderCoreDot: {
    backgroundColor: "#10b981",
    borderRadius: 999,
    height: 10,
    width: 10,
  },
  heroImageStateText: {
    color: "#6b7280",
    fontSize: 14,
    textAlign: "center",
  },
  heroImageRetryButton: {
    alignItems: "center",
    backgroundColor: "#10b981",
    borderRadius: 999,
    minHeight: 38,
    justifyContent: "center",
    paddingHorizontal: 18,
    paddingVertical: 8,
  },
  heroImageRetryButtonPressed: {
    opacity: 0.86,
  },
  heroImageRetryButtonText: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "700",
  },
  resultActionsRow: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 18,
  },
  resultActionsRowCompact: {
    gap: 8,
  },
  resultActionContent: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
  resultActionPrimary: {
    alignItems: "center",
    backgroundColor: "#10b981",
    borderRadius: 16,
    flex: 1,
    minHeight: 48,
    justifyContent: "center",
    minWidth: 0,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  resultActionCompact: {
    paddingHorizontal: 8,
  },
  resultActionPrimaryText: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "700",
    textAlign: "center",
  },
  resultActionTextCompact: {
    fontSize: 12,
  },
  resultActionSecondary: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#d1fae5",
    borderRadius: 16,
    borderWidth: 1,
    flex: 1,
    minHeight: 48,
    justifyContent: "center",
    minWidth: 0,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  resultActionSecondaryText: {
    color: "#374151",
    fontSize: 13,
    fontWeight: "700",
    textAlign: "center",
  },
  deleteActionButton: {
    borderColor: "#fecaca",
  },
  deleteActionText: {
    color: "#b91c1c",
    fontSize: 13,
    fontWeight: "700",
    textAlign: "center",
  },
  resultActionPressed: {
    opacity: 0.86,
  },
  resultActionSecondaryPressed: {
    backgroundColor: "#fafaf9",
  },
  formGroup: {
    gap: 10,
    marginTop: 6,
  },
  fieldLabelRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  fieldLabel: {
    color: "#065f46",
    fontSize: 15,
    fontWeight: "700",
  },
  helperActionChip: {
    alignItems: "center",
    backgroundColor: "#ecfdf5",
    borderColor: "#a7f3d0",
    borderRadius: 999,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 32,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  helperActionText: {
    color: "#047857",
    fontSize: 13,
    fontWeight: "700",
  },
  recipeInput: {
    backgroundColor: "#fafaf9",
    borderColor: "#d1fae5",
    borderRadius: 18,
    borderWidth: 1,
    color: "#111827",
    fontSize: 15,
    lineHeight: 22,
    minHeight: 150,
    paddingHorizontal: 14,
    paddingVertical: 14,
    paddingBottom: 54,
  },
  recipeInputWrap: {
    position: "relative",
  },
  recipeInputIconButton: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#d1fae5",
    borderRadius: 14,
    borderWidth: 1,
    bottom: 12,
    height: 36,
    justifyContent: "center",
    position: "absolute",
    right: 12,
    width: 36,
  },
  optionGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  optionRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 10,
  },
  choiceChip: {
    backgroundColor: "#f4f4f5",
    borderColor: "#d1fae5",
    borderRadius: 999,
    borderWidth: 1,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  choiceChipSelected: {
    backgroundColor: "#ecfdf5",
    borderColor: "#10b981",
  },
  choiceChipText: {
    color: "#374151",
    fontSize: 14,
    fontWeight: "600",
    textTransform: "capitalize",
  },
  choiceChipTextSelected: {
    color: "#065f46",
  },
  levelChip: {
    alignItems: "center",
    backgroundColor: "#f4f4f5",
    borderColor: "#d1fae5",
    borderRadius: 999,
    borderWidth: 1,
    height: 42,
    justifyContent: "center",
    width: 42,
  },
  levelChipSelected: {
    backgroundColor: "#ecfdf5",
    borderColor: "#10b981",
  },
  levelChipText: {
    color: "#374151",
    fontSize: 14,
    fontWeight: "700",
  },
  spiceHint: {
    color: "#065f46",
    fontSize: 14,
    fontWeight: "600",
  },
  homeActionGroup: {
    gap: 10,
    marginTop: 4,
  },
  homeBulletList: {
    gap: 10,
  },
  homeBullet: {
    color: "#374151",
    fontSize: 15,
    lineHeight: 22,
  },
  cookbookCard: {
    backgroundColor: "#fafaf9",
    borderColor: "#d1fae5",
    borderRadius: 18,
    borderWidth: 1,
    marginBottom: 12,
    padding: 14,
  },
  cookbookCardRow: {
    alignItems: "stretch",
    flexDirection: "row",
    gap: 12,
  },
  cookbookCardMainPressable: {
    flex: 1,
  },
  cookbookCardContentRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
  },
  cookbookCardImage: {
    borderRadius: 16,
    height: 72,
    width: 96,
  },
  cookbookCardImageCompact: {
    height: 64,
    width: 84,
  },
  cookbookCardImagePlaceholder: {
    alignItems: "center",
    backgroundColor: "#f0fdf4",
    borderColor: "#d1fae5",
    borderRadius: 16,
    borderWidth: 1,
    height: 72,
    justifyContent: "center",
    width: 96,
  },
  cookbookCardBody: {
    flex: 1,
    gap: 6,
    minWidth: 0,
  },
  cookbookCardActions: {
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 2,
    width: 42,
  },
  cookbookCardActionsCompact: {
    width: 34,
  },
  cookbookCardTitle: {
    color: "#111827",
    fontSize: 16,
    fontWeight: "800",
  },
  cookbookCardTitleCompact: {
    fontSize: 15,
  },
  cookbookCardDate: {
    color: "#047857",
    fontSize: 12,
    fontWeight: "700",
    textAlign: "center",
  },
  cookbookCardMeta: {
    color: "#6b7280",
    fontSize: 14,
    lineHeight: 21,
  },
  cookbookFlagRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    minHeight: 22,
  },
  cookbookFlagPill: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#d1fae5",
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: "row",
    gap: 4,
    paddingHorizontal: 8,
    paddingVertical: 3,
  },
  cookbookFlagPillText: {
    color: "#047857",
    fontSize: 11,
    fontWeight: "900",
  },
  cookbookDeleteButton: {
    alignItems: "center",
    backgroundColor: "#fff1f2",
    borderColor: "#fecdd3",
    borderRadius: 12,
    borderWidth: 1,
    height: 32,
    justifyContent: "center",
    width: 32,
  },
  cookbookDeleteButtonPressed: {
    opacity: 0.82,
  },
  cookbookFlagButton: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#d1fae5",
    borderRadius: 12,
    borderWidth: 1,
    height: 32,
    justifyContent: "center",
    width: 32,
  },
  cookbookFlagButtonActive: {
    backgroundColor: "#ef4444",
    borderColor: "#ef4444",
  },
  cookbookFlagButtonActiveWarm: {
    backgroundColor: "#b45309",
    borderColor: "#b45309",
  },
  cookbookListFooter: {
    alignItems: "center",
    justifyContent: "center",
    minHeight: 44,
    paddingBottom: 8,
    paddingTop: 4,
  },
  emptyCookbookCard: {
    gap: 12,
    paddingVertical: 6,
  },
  emptyCookbookTitle: {
    color: "#111827",
    fontSize: 18,
    fontWeight: "800",
  },
  emptyCookbookCopy: {
    color: "#4b5563",
    fontSize: 15,
    lineHeight: 23,
  },
  statusCopy: {
    color: "#4b5563",
    fontSize: 15,
    lineHeight: 23,
  },
  brandHeader: {
    alignItems: "center",
    alignSelf: "flex-start",
    flexDirection: "row",
    gap: 8,
    minHeight: 42,
  },
  brandHeaderCompact: {
    minHeight: 36,
  },
  brandHeaderLogo: {
    height: 42,
    resizeMode: "contain",
    width: 42,
  },
  brandHeaderLogoCompact: {
    height: 34,
    width: 34,
  },
  brandHeaderText: {
    color: "#111827",
    fontSize: 22,
    fontWeight: "800",
    lineHeight: 28,
  },
  brandHeaderTextCompact: {
    fontSize: 19,
    lineHeight: 24,
  },
  brandHeaderAccent: {
    color: "#047857",
  },
  profileContent: {
    paddingBottom: 24,
    paddingHorizontal: 20,
    paddingTop: 10,
  },
  profileTopBar: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  profileCreditsPill: {
    alignItems: "center",
    backgroundColor: "#ecfdf5",
    borderColor: "#d1fae5",
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: "row",
    gap: 6,
    minHeight: 34,
    paddingHorizontal: 12,
  },
  profileCreditsText: {
    color: "#047857",
    fontSize: 14,
    fontWeight: "900",
  },
  profileHeroCard: {
    backgroundColor: "#ffffff",
    borderColor: "#d1fae5",
    borderRadius: 26,
    borderWidth: 1,
    gap: 14,
    marginBottom: 18,
    padding: 18,
    shadowColor: "#065f46",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.08,
    shadowRadius: 18,
  },
  profileHeroHeader: {
    alignItems: "center",
    flexDirection: "row",
    gap: 16,
  },
  profileAvatarWrap: {
    position: "relative",
  },
  profileAvatar: {
    alignItems: "center",
    backgroundColor: "#d1fae5",
    borderColor: "#a7f3d0",
    borderRadius: 999,
    borderWidth: 1,
    height: 82,
    justifyContent: "center",
    overflow: "hidden",
    width: 82,
  },
  profileAvatarMedium: {
    height: 64,
    width: 64,
  },
  profileAvatarImage: {
    height: 82,
    width: 82,
  },
  profileAvatarImageMedium: {
    height: 64,
    width: 64,
  },
  profileAvatarInitials: {
    color: "#047857",
    fontSize: 27,
    fontWeight: "900",
  },
  profileAvatarInitialsMedium: {
    fontSize: 21,
  },
  profileAvatarEditButton: {
    alignItems: "center",
    backgroundColor: "#111827",
    borderColor: "#ffffff",
    borderRadius: 999,
    borderWidth: 2,
    bottom: -1,
    height: 30,
    justifyContent: "center",
    position: "absolute",
    right: -1,
    width: 30,
  },
  profileHeroText: {
    flex: 1,
    gap: 6,
    minWidth: 0,
  },
  profileTitle: {
    color: "#111827",
    fontSize: 25,
    fontWeight: "900",
    lineHeight: 31,
  },
  profileSubtitle: {
    color: "#6b7280",
    fontSize: 14,
    fontWeight: "600",
    lineHeight: 20,
  },
  profileEditButton: {
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "#ecfdf5",
    borderColor: "#a7f3d0",
    borderRadius: 999,
    borderWidth: 1,
    minHeight: 34,
    justifyContent: "center",
    paddingHorizontal: 14,
  },
  profileEditButtonText: {
    color: "#047857",
    fontSize: 13,
    fontWeight: "900",
  },
  profileAuthButtonGroup: {
    alignItems: "flex-start",
    gap: 8,
  },
  profileAppleSignInButton: {
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "#09090b",
    borderColor: "#09090b",
    borderRadius: 999,
    borderWidth: 1,
    flexDirection: "row",
    gap: 6,
    minHeight: 34,
    justifyContent: "center",
    paddingHorizontal: 14,
  },
  profileAppleSignInButtonText: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "900",
  },
  profileSectionHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 10,
    paddingHorizontal: 2,
  },
  profileSectionTitle: {
    color: "#111827",
    fontSize: 18,
    fontWeight: "900",
  },
  profileUsageGrid: {
    flexDirection: "row",
    gap: 10,
    marginBottom: 18,
  },
  profileUsageCard: {
    alignItems: "center",
    backgroundColor: "#ecfdf5",
    borderColor: "#d1fae5",
    borderRadius: 18,
    borderWidth: 1,
    flex: 1,
    minHeight: 118,
    justifyContent: "center",
    paddingHorizontal: 8,
    paddingVertical: 12,
  },
  profileUsageCardWarm: {
    backgroundColor: "#fff7ed",
    borderColor: "#fed7aa",
  },
  profileUsageCardBlue: {
    backgroundColor: "#eff6ff",
    borderColor: "#bfdbfe",
  },
  profileUsageIcon: {
    alignItems: "center",
    backgroundColor: "#d1fae5",
    borderRadius: 999,
    height: 38,
    justifyContent: "center",
    marginBottom: 8,
    width: 38,
  },
  profileUsageIconWarm: {
    backgroundColor: "#ffedd5",
  },
  profileUsageIconBlue: {
    backgroundColor: "#dbeafe",
  },
  profileUsageValue: {
    color: "#111827",
    fontSize: 27,
    fontWeight: "900",
    lineHeight: 32,
  },
  profileUsageLabel: {
    color: "#047857",
    fontSize: 12,
    fontWeight: "900",
    textAlign: "center",
  },
  profileUsageLabelWarm: {
    color: "#c2410c",
  },
  profileUsageLabelBlue: {
    color: "#1d4ed8",
  },
  profileCreditPurchaseCard: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#d1fae5",
    borderRadius: 20,
    borderWidth: 1,
    flexDirection: "row",
    gap: 12,
    marginBottom: 18,
    paddingHorizontal: 16,
    paddingVertical: 14,
    shadowColor: "#065f46",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.06,
    shadowRadius: 16,
  },
  profileCreditPurchaseTextWrap: {
    flex: 1,
    gap: 4,
    minWidth: 0,
  },
  profileCreditPurchaseTitle: {
    color: "#111827",
    fontSize: 15,
    fontWeight: "900",
  },
  profileCreditPurchaseCopy: {
    color: "#6b7280",
    fontSize: 12,
    fontWeight: "600",
    lineHeight: 17,
  },
  profileBuyCreditsButton: {
    alignItems: "center",
    backgroundColor: "#047857",
    borderRadius: 999,
    justifyContent: "center",
    minHeight: 38,
    minWidth: 102,
    paddingHorizontal: 14,
  },
  profileBuyCreditsButtonDisabled: {
    opacity: 0.56,
  },
  profileBuyCreditsButtonText: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "900",
  },
  profileCreditPurchaseMessage: {
    color: "#b45309",
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 18,
    marginBottom: 14,
    paddingHorizontal: 4,
  },
  profileCreditInfoCard: {
    backgroundColor: "#f8fffb",
    borderColor: "#d1fae5",
    borderRadius: 18,
    borderWidth: 1,
    marginBottom: 14,
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  profileCreditInfoCardPressed: {
    opacity: 0.82,
  },
  profileCreditInfoHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
  },
  profileCreditInfoTitleRow: {
    alignItems: "center",
    flex: 1,
    flexDirection: "row",
    gap: 10,
    minWidth: 0,
  },
  profileCreditInfoIcon: {
    alignItems: "center",
    backgroundColor: "#d1fae5",
    borderRadius: 999,
    height: 34,
    justifyContent: "center",
    width: 34,
  },
  profileCreditInfoTextWrap: {
    flex: 1,
    gap: 2,
    minWidth: 0,
  },
  profileCreditInfoTitle: {
    color: "#064e3b",
    fontSize: 14,
    fontWeight: "900",
  },
  profileCreditInfoSummary: {
    color: "#6b7280",
    fontSize: 12,
    fontWeight: "700",
    lineHeight: 17,
  },
  profileCreditInfoDetails: {
    borderTopColor: "#d1fae5",
    borderTopWidth: 1,
    gap: 9,
    marginTop: 12,
    paddingTop: 12,
  },
  profileCreditInfoDetailRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 10,
  },
  profileCreditInfoDetailLabel: {
    color: "#374151",
    flex: 1,
    fontSize: 13,
    fontWeight: "800",
  },
  profileCreditInfoDetailValue: {
    color: "#047857",
    fontSize: 13,
    fontWeight: "900",
  },
  profileCreditInfoNote: {
    color: "#6b7280",
    fontSize: 12,
    fontWeight: "600",
    lineHeight: 17,
  },
  profileCreditSheetSubtitle: {
    color: "#6b7280",
    fontSize: 13,
    fontWeight: "600",
    lineHeight: 18,
    marginTop: 4,
    maxWidth: 260,
  },
  profileCreditSheetLoading: {
    alignItems: "center",
    gap: 10,
    justifyContent: "center",
    minHeight: 120,
  },
  profileCreditPackList: {
    flexDirection: "row",
    gap: 8,
  },
  profileCreditPackCard: {
    backgroundColor: "#ffffff",
    borderColor: "#d1fae5",
    borderRadius: 16,
    borderWidth: 1,
    flex: 1,
    gap: 7,
    minHeight: 124,
    paddingHorizontal: 10,
    paddingVertical: 12,
  },
  profileCreditPackCardSelected: {
    backgroundColor: "#ecfdf5",
    borderColor: "#10b981",
  },
  profileCreditPackLabel: {
    color: "#111827",
    fontSize: 13,
    fontWeight: "900",
    lineHeight: 17,
    textAlign: "center",
  },
  profileCreditPackLabelSelected: {
    color: "#065f46",
  },
  profileCreditPackCredits: {
    color: "#6b7280",
    fontSize: 12,
    fontWeight: "700",
    textAlign: "center",
  },
  profileCreditPackPrice: {
    color: "#111827",
    fontSize: 18,
    fontWeight: "900",
    marginTop: "auto",
    textAlign: "center",
  },
  profileCreditPackPriceSelected: {
    color: "#047857",
  },
  profileStatsShadow: {
    marginBottom: 18,
    shadowColor: "#065f46",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.06,
    shadowRadius: 16,
  },
  profileStatsCard: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#d1fae5",
    borderRadius: 20,
    borderWidth: 1,
    flexDirection: "row",
    gap: 14,
    paddingHorizontal: 16,
    paddingVertical: 14,
  },
  profileStatsValue: {
    color: "#047857",
    fontSize: 28,
    fontWeight: "900",
    minWidth: 42,
    textAlign: "center",
  },
  profileStatsTextWrap: {
    flex: 1,
    gap: 3,
  },
  profileStatsTitle: {
    color: "#111827",
    fontSize: 15,
    fontWeight: "900",
  },
  profileStatsCopy: {
    color: "#6b7280",
    fontSize: 12,
    fontWeight: "600",
    lineHeight: 17,
  },
  profileRowsCard: {
    backgroundColor: "#ffffff",
    borderColor: "#d1fae5",
    borderRadius: 22,
    borderWidth: 1,
    marginBottom: 18,
    overflow: "hidden",
  },
  profileRow: {
    alignItems: "center",
    borderBottomColor: "#d1fae5",
    borderBottomWidth: StyleSheet.hairlineWidth,
    flexDirection: "row",
    gap: 12,
    minHeight: 54,
    paddingHorizontal: 16,
    paddingVertical: 10,
  },
  profileRowPressed: {
    opacity: 0.76,
  },
  profileRowIcon: {
    alignItems: "center",
    backgroundColor: "#ecfdf5",
    borderRadius: 999,
    height: 30,
    justifyContent: "center",
    width: 30,
  },
  profileRowIconDanger: {
    backgroundColor: "#fee2e2",
  },
  profileRowText: {
    color: "#111827",
    flex: 1,
    fontSize: 15,
    fontWeight: "800",
  },
  profileRowTextDanger: {
    color: "#991b1b",
  },
  profileVersionText: {
    color: "#9ca3af",
    fontSize: 12,
    fontWeight: "700",
    paddingHorizontal: 4,
    paddingTop: 2,
  },
  profileModalBackdrop: {
    backgroundColor: "rgba(17, 24, 39, 0.38)",
    flex: 1,
    justifyContent: "flex-end",
  },
  profileEditSheet: {
    backgroundColor: "#f8faf7",
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    gap: 12,
    maxHeight: "92%",
    paddingBottom: 26,
    paddingHorizontal: 20,
    paddingTop: 18,
  },
  profileEditTopRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  profileEditTitle: {
    color: "#111827",
    fontSize: 24,
    fontWeight: "900",
  },
  profileEditCloseButton: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#d1fae5",
    borderRadius: 999,
    borderWidth: 1,
    height: 38,
    justifyContent: "center",
    width: 38,
  },
  profileEditAvatarArea: {
    alignItems: "center",
    paddingBottom: 6,
    paddingTop: 8,
  },
  profileFieldLabel: {
    color: "#065f46",
    fontSize: 14,
    fontWeight: "800",
  },
  profileNameInput: {
    backgroundColor: "#ffffff",
    borderColor: "#d1fae5",
    borderRadius: 16,
    borderWidth: 1,
    color: "#111827",
    fontSize: 16,
    fontWeight: "700",
    minHeight: 50,
    paddingHorizontal: 14,
  },
  profileReadonlyField: {
    backgroundColor: "#f9fafb",
    borderColor: "#d1fae5",
    borderRadius: 16,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 50,
    paddingHorizontal: 14,
  },
  profileReadonlyFieldText: {
    color: "#6b7280",
    fontSize: 15,
    fontWeight: "700",
  },
  profileSaveButton: {
    alignItems: "center",
    backgroundColor: "#047857",
    borderRadius: 999,
    minHeight: 52,
    justifyContent: "center",
    marginTop: 2,
  },
  profileSaveButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "900",
  },
  activityEmptyIcon: {
    alignItems: "center",
    backgroundColor: "#ecfdf5",
    borderColor: "#a7f3d0",
    borderRadius: 999,
    borderWidth: 1,
    height: 58,
    justifyContent: "center",
    width: 58,
  },
  dashboardContent: {
    paddingBottom: 12,
    paddingHorizontal: 20,
    paddingTop: 10,
  },
  dashboardTopBar: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
    justifyContent: "space-between",
    marginBottom: 12,
  },
  dashboardGreetingBlock: {
    gap: 5,
    marginBottom: 22,
  },
  dashboardGreeting: {
    color: "#111827",
    fontSize: 26,
    fontWeight: "900",
    lineHeight: 31,
  },
  dashboardGreetingCopy: {
    color: "#6b7280",
    fontSize: 15,
    fontWeight: "600",
  },
  dashboardActionRow: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 20,
  },
  dashboardPrimaryAction: {
    alignItems: "center",
    backgroundColor: "#047857",
    borderRadius: 20,
    flex: 1,
    flexDirection: "row",
    gap: 10,
    minHeight: 76,
    paddingHorizontal: 12,
    shadowColor: "#065f46",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.16,
    shadowRadius: 18,
  },
  dashboardPrimaryIcon: {
    alignItems: "center",
    borderColor: "rgba(255,255,255,0.76)",
    borderRadius: 999,
    borderWidth: 2,
    height: 32,
    justifyContent: "center",
    width: 32,
  },
  dashboardActionTextWrap: {
    flex: 1,
    minWidth: 0,
  },
  dashboardPrimaryActionTitle: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "900",
  },
  dashboardPrimaryActionCopy: {
    color: "rgba(255,255,255,0.86)",
    fontSize: 10,
    fontWeight: "700",
    marginTop: 3,
  },
  dashboardSecondaryAction: {
    alignItems: "center",
    backgroundColor: "#f0fdf4",
    borderColor: "#d1fae5",
    borderRadius: 20,
    borderWidth: 1,
    flex: 1,
    flexDirection: "row",
    gap: 10,
    minHeight: 76,
    paddingHorizontal: 12,
  },
  dashboardSecondaryIcon: {
    alignItems: "center",
    borderColor: "#047857",
    borderRadius: 10,
    borderWidth: 2,
    height: 32,
    justifyContent: "center",
    width: 32,
  },
  dashboardSecondaryActionTitle: {
    color: "#111827",
    fontSize: 16,
    fontWeight: "900",
  },
  dashboardSecondaryActionCopy: {
    color: "#6b7280",
    fontSize: 10,
    fontWeight: "700",
    marginTop: 3,
  },
  dashboardSectionHeader: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 8,
  },
  dashboardSectionTitle: {
    color: "#111827",
    fontSize: 19,
    fontWeight: "900",
  },
  dashboardViewAll: {
    color: "#047857",
    fontSize: 13,
    fontWeight: "900",
  },
  dashboardRecipeRow: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 20,
  },
  dashboardRecipeCard: {
    backgroundColor: "#ffffff",
    borderColor: "#d1fae5",
    borderRadius: 18,
    borderWidth: 1,
    flex: 1,
    overflow: "hidden",
    shadowColor: "#065f46",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 14,
  },
  dashboardRecipeImageWrap: {
    aspectRatio: 0.96,
    backgroundColor: "#ecfdf5",
    position: "relative",
  },
  dashboardRecipeImage: {
    height: "100%",
    width: "100%",
  },
  dashboardRecipeFallback: {
    alignItems: "center",
    flex: 1,
    justifyContent: "center",
  },
  dashboardHeartBadge: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderRadius: 999,
    height: 34,
    justifyContent: "center",
    position: "absolute",
    right: 8,
    top: 8,
    width: 34,
  },
  dashboardRecipeBadgeRow: {
    flexDirection: "row",
    gap: 6,
    position: "absolute",
    right: 8,
    top: 8,
  },
  dashboardRecipeStateBadge: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderRadius: 999,
    height: 34,
    justifyContent: "center",
    width: 34,
  },
  dashboardRecipeBody: {
    gap: 5,
    minHeight: 92,
    padding: 11,
  },
  dashboardRecipeTitle: {
    color: "#111827",
    fontSize: 14,
    fontWeight: "900",
    lineHeight: 18,
  },
  dashboardRecipeMeta: {
    color: "#6b7280",
    fontSize: 12,
    fontWeight: "700",
  },
  dashboardUsedPill: {
    alignItems: "center",
    alignSelf: "flex-end",
    backgroundColor: "#ecfdf5",
    borderRadius: 999,
    flexDirection: "row",
    gap: 4,
    marginTop: "auto",
    paddingHorizontal: 9,
    paddingVertical: 6,
  },
  dashboardUsedPillText: {
    color: "#047857",
    fontSize: 11,
    fontWeight: "900",
  },
  dashboardEmptyRecentCard: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#d1fae5",
    borderRadius: 20,
    borderWidth: 1,
    flex: 1,
    gap: 8,
    padding: 20,
  },
  dashboardEmptyTitle: {
    color: "#111827",
    fontSize: 16,
    fontWeight: "900",
  },
  dashboardEmptyCopy: {
    color: "#6b7280",
    fontSize: 13,
    fontWeight: "600",
    lineHeight: 18,
    textAlign: "center",
  },
  recentFusionCard: {
    backgroundColor: "#fafaf9",
    borderColor: "#d1fae5",
    borderRadius: 18,
    borderWidth: 1,
    gap: 12,
    marginBottom: 12,
    padding: 12,
  },
  recentFusionMain: {
    alignItems: "center",
    flexDirection: "row",
    gap: 12,
  },
  recentFusionImage: {
    borderRadius: 16,
    height: 82,
    width: 104,
  },
  recentFusionImagePlaceholder: {
    alignItems: "center",
    backgroundColor: "#f0fdf4",
    borderColor: "#d1fae5",
    borderRadius: 16,
    borderWidth: 1,
    height: 82,
    justifyContent: "center",
    width: 104,
  },
  recentFusionBody: {
    flex: 1,
    gap: 6,
    minWidth: 0,
  },
  recentFusionActionRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
  },
  recentFusionActionSpacer: {
    flex: 1,
    minWidth: 4,
  },
  recentFusionActionDate: {
    color: "#047857",
    flexShrink: 0,
    fontSize: 12,
    fontWeight: "900",
    maxWidth: 58,
    textAlign: "right",
  },
  recentFusionActionButton: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#d1fae5",
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    flexDirection: "row",
    gap: 6,
    justifyContent: "center",
    minHeight: 40,
    paddingHorizontal: 10,
  },
  recentFusionSaveButton: {
    flex: 0,
    width: 104,
  },
  recentFusionActionButtonActive: {
    backgroundColor: "#10b981",
    borderColor: "#10b981",
  },
  recentFusionActionText: {
    color: "#047857",
    fontSize: 12,
    fontWeight: "900",
  },
  recentFusionActionTextActive: {
    color: "#ffffff",
  },
  recentFusionIconButton: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#d1fae5",
    borderRadius: 14,
    borderWidth: 1,
    height: 40,
    justifyContent: "center",
    width: 44,
  },
  dashboardCookbookGrid: {
    flexDirection: "row",
    gap: 8,
  },
  dashboardCookbookTile: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#d1fae5",
    borderRadius: 16,
    borderWidth: 1,
    flex: 1,
    gap: 6,
    minHeight: 96,
    justifyContent: "center",
    paddingHorizontal: 6,
    paddingVertical: 8,
  },
  dashboardCookbookTileTitle: {
    color: "#111827",
    fontSize: 11,
    fontWeight: "900",
    textAlign: "center",
  },
  dashboardCookbookTileMeta: {
    color: "#6b7280",
    fontSize: 10,
    fontWeight: "700",
    textAlign: "center",
  },
  kicker: {
    alignSelf: "flex-start",
    backgroundColor: "#10b981",
    borderRadius: 999,
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "700",
    overflow: "hidden",
    paddingHorizontal: 12,
    paddingVertical: 6,
    textTransform: "uppercase",
  },
  title: {
    color: "#111827",
    fontSize: 34,
    fontWeight: "800",
    lineHeight: 40,
  },
  titleCompact: {
    fontSize: 30,
    lineHeight: 36,
  },
  titleVeryCompact: {
    fontSize: 27,
    lineHeight: 33,
  },
  meta: {
    color: "#c2410c",
    fontSize: 14,
    fontWeight: "600",
  },
  pendingCopy: {
    color: "#4b5563",
    fontSize: 16,
    lineHeight: 24,
  },
  summary: {
    color: "#4b5563",
    fontSize: 17,
    lineHeight: 28,
  },
  captureCard: {
    backgroundColor: "#ffffff",
    borderColor: "#d1fae5",
    borderRadius: 28,
    borderWidth: 1,
    overflow: "hidden",
    width: 520,
  },
  visibleCard: {
    backgroundColor: "#ffffff",
    borderColor: "#d1fae5",
    borderRadius: 24,
    borderWidth: 1,
    marginBottom: 16,
    padding: 18,
  },
  importCard: {
    backgroundColor: "#ffffff",
    borderColor: "#d1fae5",
    borderRadius: 24,
    borderWidth: 1,
    gap: 14,
    marginBottom: 16,
    padding: 18,
  },
  compactImportCard: {
    backgroundColor: "#fafaf9",
    borderColor: "#d1fae5",
    borderRadius: 20,
    borderWidth: 1,
    gap: 12,
    marginTop: 8,
    overflow: "hidden",
    padding: 12,
  },
  compactImportHeader: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: 12,
  },
  compactImportImage: {
    borderRadius: 14,
    width: 84,
  },
  compactImportImageCompact: {
    width: 72,
  },
  compactImportTextBlock: {
    flex: 1,
    gap: 4,
  },
  imageViewerOverlay: {
    alignItems: "center",
    backgroundColor: "rgba(17, 24, 39, 0.94)",
    flex: 1,
    justifyContent: "center",
  },
  imageViewerSafeArea: {
    flex: 1,
    justifyContent: "center",
    width: "100%",
  },
  imageViewerBody: {
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 20,
    width: "100%",
  },
  imageViewerImage: {
    aspectRatio: 4 / 3,
    borderRadius: 18,
    maxHeight: "85%",
    width: "100%",
  },
  hiddenCaptureHost: {
    left: -10000,
    position: "absolute",
    top: 0,
  },
  captureHeader: {
    backgroundColor: "#ecfdf5",
    gap: 8,
    paddingHorizontal: 22,
    paddingVertical: 22,
  },
  captureHeroImage: {
    aspectRatio: 4 / 3,
    width: "100%",
  },
  captureHeroImageFallback: {
    alignItems: "center",
    aspectRatio: 4 / 3,
    backgroundColor: "#fafaf9",
    borderBottomColor: "#d1fae5",
    borderBottomWidth: 1,
    justifyContent: "center",
    paddingHorizontal: 18,
  },
  captureHeroImageFallbackText: {
    color: "#6b7280",
    fontSize: 14,
    textAlign: "center",
  },
  captureBrandRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  captureBrand: {
    color: "#065f46",
    fontSize: 18,
    fontWeight: "800",
  },
  captureStamp: {
    backgroundColor: "#ffffff",
    borderRadius: 999,
    color: "#047857",
    fontSize: 12,
    fontWeight: "700",
    overflow: "hidden",
    paddingHorizontal: 10,
    paddingVertical: 6,
    textTransform: "uppercase",
  },
  captureEyebrow: {
    color: "#c2410c",
    fontSize: 14,
    fontWeight: "700",
    textTransform: "uppercase",
  },
  captureTitle: {
    color: "#111827",
    fontSize: 34,
    fontWeight: "800",
    lineHeight: 40,
  },
  captureSubtitle: {
    color: "#4b5563",
    fontSize: 17,
    lineHeight: 25,
  },
  card: {
    gap: 2,
    padding: 22,
  },
  capturePanel: {
    backgroundColor: "#fafaf9",
    borderRadius: 18,
    padding: 16,
  },
  capturePanelTitle: {
    color: "#065f46",
    fontSize: 18,
    fontWeight: "800",
    marginBottom: 10,
  },
  sectionTitle: {
    color: "#065f46",
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 12,
  },
  sectionHeaderRow: {
    alignItems: "center",
    flexDirection: "row",
    gap: 8,
    marginBottom: 12,
  },
  sectionHeaderTitle: {
    color: "#065f46",
    fontSize: 18,
    fontWeight: "700",
    lineHeight: 22,
  },
  badgeRow: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  badge: {
    backgroundColor: "#ecfdf5",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
  },
  badgeText: {
    color: "#065f46",
    fontSize: 13,
    fontWeight: "600",
  },
  captureTagGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
  },
  captureTag: {
    backgroundColor: "#ffffff",
    borderColor: "#d1fae5",
    borderRadius: 14,
    borderWidth: 1,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  captureTagLabel: {
    color: "#065f46",
    fontSize: 14,
    fontWeight: "600",
  },
  divider: {
    backgroundColor: "#e4e4e7",
    height: 1,
    marginVertical: 16,
  },
  listRow: {
    backgroundColor: "#f0fdf4",
    borderColor: "#dcfce7",
    borderRadius: 16,
    borderWidth: 1,
    gap: 2,
    marginBottom: 10,
    padding: 12,
  },
  listPrimary: {
    color: "#111827",
    fontSize: 15,
    fontWeight: "600",
  },
  listSecondary: {
    color: "#6b7280",
    fontSize: 13,
  },
  swapCard: {
    backgroundColor: "#ecfdf5",
    borderColor: "#d1fae5",
    borderRadius: 18,
    borderWidth: 1,
    gap: 6,
    marginBottom: 10,
    padding: 14,
  },
  swapTitle: {
    color: "#111827",
    fontSize: 15,
    fontWeight: "600",
  },
  swapReason: {
    color: "#6b7280",
    fontSize: 13,
    lineHeight: 19,
  },
  shoppingRow: {
    alignItems: "flex-start",
    borderRadius: 16,
    flexDirection: "row",
    gap: 12,
    marginBottom: 12,
    paddingHorizontal: 6,
    paddingVertical: 6,
  },
  shoppingRowChecked: {
    opacity: 0.72,
  },
  shoppingCheckbox: {
    alignItems: "center",
    borderColor: "#10b981",
    borderRadius: 999,
    borderWidth: 1.5,
    height: 20,
    justifyContent: "center",
    marginTop: 2,
    width: 20,
  },
  shoppingCheckboxChecked: {
    backgroundColor: "#10b981",
    borderColor: "#10b981",
  },
  shoppingCheckboxTick: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "800",
    lineHeight: 12,
  },
  shoppingTextBlock: {
    flex: 1,
  },
  checkedPrimaryText: {
    color: "#6b7280",
    textDecorationLine: "line-through",
  },
  checkedSecondaryText: {
    color: "#9ca3af",
    textDecorationLine: "line-through",
  },
  nutritionCard: {
    backgroundColor: "#fff7ed",
    borderColor: "#fed7aa",
    borderRadius: 18,
    borderWidth: 1,
    padding: 14,
  },
  nutritionCopy: {
    color: "#7c2d12",
    fontSize: 14,
    lineHeight: 21,
  },
  emptySectionCopy: {
    color: "#6b7280",
    fontSize: 14,
    lineHeight: 21,
  },
  stepRow: {
    flexDirection: "row",
    gap: 12,
    marginBottom: 14,
  },
  stepIndex: {
    color: "#10b981",
    fontSize: 16,
    fontWeight: "800",
    width: 18,
  },
  stepText: {
    color: "#374151",
    flex: 1,
    fontSize: 15,
    lineHeight: 23,
  },
  captureNote: {
    backgroundColor: "#fff7ed",
    borderRadius: 18,
    marginTop: 2,
    padding: 14,
  },
  captureNoteLabel: {
    color: "#c2410c",
    fontSize: 13,
    fontWeight: "800",
    marginBottom: 6,
    textTransform: "uppercase",
  },
  captureNoteText: {
    color: "#7c2d12",
    fontSize: 15,
    lineHeight: 22,
  },
  captureFooter: {
    alignItems: "center",
    marginTop: 16,
    paddingHorizontal: 8,
  },
  captureFooterTitle: {
    color: "#111827",
    fontSize: 15,
    fontWeight: "800",
    marginBottom: 4,
    textAlign: "center",
  },
  captureFooterText: {
    color: "#6b7280",
    fontSize: 13,
    lineHeight: 19,
    textAlign: "center",
  },
  importCopy: {
    color: "#4b5563",
    fontSize: 15,
    lineHeight: 23,
  },
  importActions: {
    gap: 10,
  },
  previewCard: {
    backgroundColor: "#fafaf9",
    borderColor: "#d1fae5",
    borderRadius: 20,
    borderWidth: 1,
    gap: 12,
    overflow: "hidden",
    padding: 12,
  },
  previewImage: {
    borderRadius: 16,
    width: "100%",
  },
  previewTextBlock: {
    gap: 4,
  },
  previewActions: {
    gap: 10,
  },
  previewTitle: {
    color: "#111827",
    fontSize: 17,
    fontWeight: "700",
  },
  previewMeta: {
    color: "#047857",
    fontSize: 13,
    fontWeight: "600",
  },
  previewCopy: {
    color: "#6b7280",
    fontSize: 14,
    lineHeight: 21,
  },
  extractedTextInput: {
    backgroundColor: "#fafaf9",
    borderColor: "#d1fae5",
    borderRadius: 18,
    borderWidth: 1,
    color: "#111827",
    fontSize: 15,
    lineHeight: 22,
    minHeight: 240,
    paddingHorizontal: 14,
    paddingVertical: 14,
  },
  modalSafeArea: {
    backgroundColor: "#f6faf7",
    flex: 1,
  },
  creditGateRoot: {
    backgroundColor: "#000000",
    flex: 1,
  },
  creditGateBackground: {
    flex: 1,
  },
  creditGateBackgroundImage: {
    resizeMode: "cover",
  },
  creditGateOverlay: {
    backgroundColor: "rgba(7, 16, 13, 0.3)",
    flex: 1,
  },
  creditGateTopScrim: {
    backgroundColor: "rgba(7, 16, 13, 0.38)",
    height: 190,
    left: 0,
    position: "absolute",
    right: 0,
    top: 0,
  },
  creditGateSheet: {
    backgroundColor: "transparent",
    flex: 1,
  },
  creditGateSheetCompact: {
    gap: 12,
    paddingHorizontal: 16,
  },
  creditGateMainContent: {
    gap: 18,
  },
  creditGateFooter: {
    marginTop: "auto",
  },
  modalKeyboardWrap: {
    flex: 1,
  },
  modalScrollView: {
    flex: 1,
  },
  modalScrollContent: {
    flexGrow: 1,
    paddingBottom: 40,
  },
  modalSheet: {
    backgroundColor: "#f6faf7",
    gap: 16,
    paddingHorizontal: 20,
    paddingTop: 28,
  },
  modalHeader: {
    alignItems: "flex-start",
    flexDirection: "row",
    justifyContent: "space-between",
  },
  modalHeaderCompact: {
    gap: 12,
  },
  modalHeaderTextBlock: {
    flex: 1,
    marginRight: 12,
  },
  modalTitle: {
    color: "#111827",
    fontSize: 26,
    fontWeight: "800",
  },
  modalSubtitle: {
    color: "#6b7280",
    fontSize: 15,
    lineHeight: 23,
    marginTop: 4,
    maxWidth: 300,
  },
  creditGateHeaderTitle: {
    color: "#f8fafc",
    textShadowColor: "rgba(0, 0, 0, 0.6)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 4,
  },
  creditGateHeaderTitleCompact: {
    fontSize: 24,
  },
  creditGateHeaderTitleVeryCompact: {
    fontSize: 22,
  },
  creditGateHeaderSubtitle: {
    color: "rgba(243, 244, 246, 0.92)",
    maxWidth: 300,
    textShadowColor: "rgba(0, 0, 0, 0.55)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 3,
  },
  creditGateHeaderSubtitleCompact: {
    fontSize: 14,
    lineHeight: 21,
    maxWidth: 270,
  },
  creditGateHeaderSubtitleVeryCompact: {
    fontSize: 13,
    lineHeight: 19,
    maxWidth: 240,
  },
  modalCloseButton: {
    alignItems: "center",
    alignSelf: "flex-start",
    backgroundColor: "#ffffff",
    borderColor: "#d1fae5",
    borderRadius: 14,
    borderWidth: 1,
    justifyContent: "center",
    minHeight: 42,
    minWidth: 72,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  modalCloseButtonCompact: {
    minHeight: 38,
    minWidth: 68,
    paddingHorizontal: 10,
    paddingVertical: 8,
  },
  modalCloseLabel: {
    color: "#111827",
    fontSize: 14,
    fontWeight: "700",
  },
  modalPreviewCard: {
    backgroundColor: "#ffffff",
    borderColor: "#d1fae5",
    borderRadius: 22,
    borderWidth: 1,
    gap: 12,
    padding: 14,
  },
  creditGateIntroCard: {
    backgroundColor: "#ffffff",
    borderColor: "#d1fae5",
    borderRadius: 22,
    borderWidth: 1,
    gap: 12,
    padding: 18,
  },
  creditGateIntroCardCompact: {
    borderRadius: 18,
    gap: 10,
    padding: 14,
  },
  creditGateIntroCopy: {
    color: "#6b7280",
    fontSize: 14,
    lineHeight: 21,
  },
  creditGateIntroPoints: {
    gap: 8,
  },
  creditGateIntroPoint: {
    color: "#374151",
    fontSize: 14,
    lineHeight: 20,
  },
  creditGateCheckMark: {
    color: "#10b981",
    fontWeight: "800",
  },
  creditPackList: {
    flexDirection: "row",
    gap: 8,
    marginTop: 12,
  },
  creditPackListCompact: {
    gap: 6,
    marginTop: 10,
  },
  creditPackListVeryCompact: {
    gap: 5,
    marginTop: 8,
  },
  creditPackCard: {
    backgroundColor: "#ffffff",
    borderColor: "#d1fae5",
    borderRadius: 16,
    borderWidth: 1,
    flex: 1,
    gap: 8,
    minHeight: 150,
    paddingHorizontal: 12,
    paddingVertical: 12,
  },
  creditPackCardCompact: {
    minHeight: 140,
    paddingHorizontal: 8,
    paddingVertical: 10,
  },
  creditPackCardVeryCompact: {
    minHeight: 132,
    paddingHorizontal: 7,
    paddingVertical: 9,
  },
  creditPackCardSelected: {
    backgroundColor: "#ecfdf5",
    borderColor: "#10b981",
  },
  creditPackCardPressed: {
    opacity: 0.9,
  },
  creditPackHeaderRow: {
    alignItems: "center",
    gap: 4,
  },
  creditPackLabel: {
    color: "#111827",
    fontSize: 13,
    fontWeight: "700",
    lineHeight: 17,
    textAlign: "center",
  },
  creditPackLabelCompact: {
    fontSize: 13,
    lineHeight: 16,
  },
  creditPackLabelVeryCompact: {
    fontSize: 12,
    lineHeight: 15,
  },
  creditPackLabelSelected: {
    color: "#065f46",
  },
  creditPackRecommendedBadge: {
    alignSelf: "center",
    backgroundColor: "#d1fae5",
    borderRadius: 999,
    marginTop: 6,
    paddingHorizontal: 10,
    paddingVertical: 5,
  },
  creditPackRecommendedBadgeCompact: {
    marginTop: 5,
    paddingHorizontal: 9,
    paddingVertical: 4,
  },
  creditPackRecommendedBadgeVeryCompact: {
    marginTop: 4,
    paddingHorizontal: 8,
    paddingVertical: 4,
  },
  creditPackRecommendedText: {
    color: "#065f46",
    fontSize: 11,
    fontWeight: "700",
  },
  creditPackRecommendedTextCompact: {
    fontSize: 10,
  },
  creditPackRecommendedTextVeryCompact: {
    fontSize: 9,
  },
  creditPackMetaRow: {
    alignItems: "center",
    gap: 3,
    marginTop: 6,
  },
  creditPackCredits: {
    color: "#374151",
    fontSize: 12,
    fontWeight: "600",
    lineHeight: 16,
    textAlign: "center",
  },
  creditPackCreditsCompact: {
    fontSize: 11,
    lineHeight: 15,
  },
  creditPackCreditsVeryCompact: {
    fontSize: 10,
    lineHeight: 14,
  },
  creditPackCreditsSelected: {
    color: "#065f46",
  },
  creditPackPrice: {
    color: "#111827",
    fontSize: 20,
    fontWeight: "700",
    letterSpacing: -0.2,
    lineHeight: 23,
    textAlign: "center",
  },
  creditPackPriceCompact: {
    fontSize: 22,
    lineHeight: 25,
  },
  creditPackPriceVeryCompact: {
    fontSize: 20,
    lineHeight: 23,
  },
  creditPackPriceSelected: {
    color: "#047857",
  },
  modalEditorCard: {
    backgroundColor: "#ffffff",
    borderColor: "#d1fae5",
    borderRadius: 22,
    borderWidth: 1,
    gap: 12,
    padding: 14,
  },
  modalSectionLabel: {
    color: "#065f46",
    fontSize: 15,
    fontWeight: "700",
  },
  creditGateIntroTitle: {
    fontSize: 26,
    textAlign: "center",
  },
  creditGateIntroTitleCompact: {
    fontSize: 24,
  },
  creditGateIntroTitleVeryCompact: {
    fontSize: 22,
  },
  modalPreviewImage: {
    borderRadius: 18,
    maxHeight: 240,
    width: "100%",
  },
  modalActions: {
    gap: 10,
    marginTop: 12,
    paddingBottom: 4,
  },
  creditGateAuthActions: {
    gap: 10,
  },
  creditGateAuthActionsCompact: {
    gap: 8,
  },
  creditGateAuthActionsSpacer: {
    height: 116,
  },
  creditGateAppleButton: {
    alignItems: "center",
    backgroundColor: "#09090b",
    borderColor: "#09090b",
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: "row",
    justifyContent: "center",
    minHeight: 56,
    paddingHorizontal: 16,
  },
  creditGateAppleIcon: {
    color: "#ffffff",
    marginRight: 12,
  },
  creditGateAppleButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "700",
  },
  creditGateGoogleButton: {
    alignItems: "center",
    backgroundColor: "#ffffff",
    borderColor: "#d1fae5",
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: "row",
    justifyContent: "center",
    minHeight: 56,
    paddingHorizontal: 16,
  },
  creditGateAuthButtonCompact: {
    minHeight: 52,
  },
  creditGateGoogleIconImage: {
    height: 20,
    marginRight: 12,
    width: 20,
  },
  creditGateGoogleButtonText: {
    color: "#111827",
    fontSize: 16,
    fontWeight: "700",
  },
  creditGateAuthButtonTextCompact: {
    fontSize: 15,
  },
  creditGateAuthButtonPressed: {
    opacity: 0.86,
  },
  creditGateHelperSpacer: {
    height: 26,
  },
  creditGateHelperSpacerCompact: {
    height: 14,
  },
  creditGateLegalRow: {
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
    marginTop: 16,
  },
  creditGateLogoutButton: {
    alignItems: "center",
    marginTop: 10,
    paddingHorizontal: 10,
    paddingVertical: 6,
  },
  creditGateLogoutText: {
    color: "#ffffff",
    fontSize: 14,
    fontWeight: "600",
  },
  creditGateLegalRowCompact: {
    marginTop: 10,
  },
  creditGateLegalLink: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "600",
  },
  creditGateLegalLinkCompact: {
    fontSize: 12,
  },
  creditGateLegalDivider: {
    color: "#ffffff",
    marginHorizontal: 10,
  },
  emptyImportState: {
    backgroundColor: "#fafaf9",
    borderColor: "#d1fae5",
    borderRadius: 20,
    borderStyle: "dashed",
    borderWidth: 1,
    gap: 6,
    padding: 16,
  },
  emptyImportTitle: {
    color: "#111827",
    fontSize: 16,
    fontWeight: "700",
  },
  emptyImportCopy: {
    color: "#6b7280",
    fontSize: 14,
    lineHeight: 21,
  },
});
